# [[Subdirectories]]
add_subdirectory("ThirdParty")

add_subdirectory("Platform")
add_subdirectory("Core")

add_subdirectory("Renderer")
add_subdirectory("Audio")
add_subdirectory("Input")
add_subdirectory("Physics")
add_subdirectory("Scripting")
add_subdirectory("Objects")
add_subdirectory("Lighting")
add_subdirectory("Animations")
add_subdirectory("Particles")
add_subdirectory("Network")
add_subdirectory("Interactive")
add_subdirectory("Editor")
