name: Eightgine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Download project"
      uses: actions/checkout@v3

    - name: "Setup Ubuntu (Dev)"
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install -y build-essential gcc-9 g++-9
        sudo apt install -y libwayland-dev libegl1-mesa-dev
        sudo apt install -y libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxfixes-dev libxi-dev
        sudo apt install -y libasound2-dev libpulse-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
        sudo update-alternatives --config gcс
        sudo update-alternatives --config g++
        sudo snap install cmake --classic

    - name: "Regenerate and Rebuild project"
      run: |
        export Eightgine=${{ github.workspace }}
        cd ${Eightgine}/Development
        rm -rf Intermediate
        mkdir Intermediate
        cd Intermediate
        /snap/bin/cmake ..
        /snap/bin/cmake --build . -- -j$(nproc)

    - name: "Package and Upload project"
      uses: actions/upload-artifact@v4
      with:
        name: Eightgine
        path: |
          Eightgine/Binaries/
          Eightgine/Resources/