name: EightgineWithEditor-macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    env:
      Eightgine: ${{ github.workspace }}

    steps:
    - name: "Checkout project"
      uses: actions/checkout@v3

    - name: "Setup macOS (Dev)"
      run: |
        brew install cmake ninja llvm
        cmake --version
        clang --version

    - name: "Regenerate and Rebuild project"
      run: |
        cd ${Eightgine}
        rm -rf Intermediate
        cmake -S . -B Intermediate -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
        cmake --build Intermediate --parallel
        ls -R

    - name: "Package and Upload project"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}
        path: |
          ${{ env.Eightgine }}/EmptyProject.app