name: EightgineWithEditor-Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    env:
      Eightgine: ${{ github.workspace }}

    steps:
    - name: "Download project"
      uses: actions/checkout@v3

    - name: "Setup Windows (Dev)"
      run: |
        choco install ninja cmake -y
        curl -L https://github.com/mstorsjo/llvm-mingw/releases/download/20250709/llvm-mingw-20250709-ucrt-x86_64.zip -o llvm-mingw.zip
        powershell -Command "Expand-Archive llvm-mingw.zip -DestinationPath C:\llvm-mingw"
        setx PATH "C:\llvm-mingw\bin;%PATH%"
        clang --version

    - name: "Regenerate and Rebuild project"
      shell: cmd
      run: |
        cd %Eightgine%\Development
        rmdir /s /q Intermediate
        cmake -S . -B Intermediate -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
        cmake --build Intermediate --parallel

    - name: "Package and Upload project"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}
        path: |
          ${{ env.Eightgine }}\Binaries\
          ${{ env.Eightgine }}\BinariesWithEditor\
          ${{ env.Eightgine }}\Resources\